### 1. Register a New User Account (Multi-Branch Ready)
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "schoolId": "6a4684d8bbe327f841fbdcd3", 
  "name": {
    "th": "สุทธิพงษ์ ผลมาก",
    "en": "Suttipong Polmag"
  },
  "email": "spolmag@gmail.com",
  "password": "password123",
  "role": "manager",
  "phoneNumber": "0895181958"
}

### 2. Login with the New Credentials
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "spolmag@gmail.com",
  "password": "password123"
}

### Register a new student/teacher
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "schoolId": "6a4b9e674dd915784e7cf926", 
  "name": {
    "th": "ณัฐวุฒิ สอนดี",
    "en": "Natthawut Sondee"
  },
  "email": "natthawut.teacher@school.com",
  "password": "teacherpassword123",
  "role": "teacher",
  "phoneNumber": "0898765432",
  "academicProfile": {
    "teacherCertification": {
      "certificationBody": "Yamaha",
      "passedGrade": "Grade 5"
    }
  }
}

### Register a new student with date of birth
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "schoolId": "6a4684d8bbe327f841fbdcd3", 
  "name": {
    "th": "เด็กหญิง มะลิ รักดี",
    "en": "Miss Mali Rakdee"
  },
  "email": "mali.student@gmail.com",
  "password": "studentpassword123",
  "role": "student",
  "phoneNumber": "0823456789",
  "dateOfBirth": "2019-04-12",
  "academicProfile": {
    "studentTrack": [
      {
        "courseId": "6a4fa2b0ad1d8c1c237e6f64",
        "currentLevel": 1
      }
    ]
  }
}

### Register a new teacher with multi grade
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "schoolId": "6a4b9e674dd915784e7cf926", 
  "name": {
    "th": "สมชาย คั้งยัง",
    "en": "Somchai Kangyang"
  },
  "email": "somchai.teacher@school.com",
  "password": "password123",
  "role": "teacher",
  "phoneNumber": "0898765432",
  "academicProfile": {
    "teacherCertifications": [
      {
        "certificationBody": "ABRSM",
        "passedGrade": "Grade 8 Piano Performance with Distinction"
      },
      {
        "certificationBody": "Yamaha",
        "passedGrade": "Grade 5 Instructor Certified Grade"
      },
      {
        "certificationBody": "Trinity",
        "passedGrade": "ATCL Recital Diploma"
      }
    ]
  }
}

### Admin/Manager get user profile by ID
GET http://localhost:5000/api/users/6a510011bf2a54a0212f2bf9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTBmY2Y0YzYwMzUzNjk2NWU1NzUwOCIsImlhdCI6MTc4MzY5NDc5NX0.O7rx3OZyxOiIc7GN0XsuukuP1IA0jinl-otQyfNqawo

### Get current user profile
GET http://localhost:5000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDkwOGEyYzBlZGI3MmQwMjJlMDQxOSIsImlhdCI6MTc4MzMzNTM3NX0._11FBcfMfiO6n0uDhoRPvPdmp_-udgSI0pQi3ZEpkFY

### Switch branch (User must have more than 1 school in schools key in user document)
PATCH http://localhost:5000/api/auth/switch-branch
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDkwOGEyYzBlZGI3MmQwMjJlMDQxOSIsImlhdCI6MTc4MzM0MjE2M30.Nxj6ZxlzoK0MyhCNo_58uJMBUujDQubS41EfdP1unyo

{
  "schoolId": "6a4b9e674dd915784e7cf926"
}

### Admin add new branch for "teacher" role user. *Need logon as admin to get permission
PATCH http://localhost:5000/api/users/6a4908a2c0edb72d022e0419/add-branch
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNGJhYzE1YzdlZDZkOTExN2M4NTc1MSIsImlhdCI6MTc4MzM0NTA1Mn0.KmL6hs2jm8qcYk-rIp_QdMZynHoMiIXCFaFIOOgmUR0

{
  "schoolId": "6a4b9e674dd915784e7cf926"
}