//Need user as admin or teacher role to create new class
### User login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "spolmag@gmail.com",
  "password": "password1234"
}

### Schedule an Advanced Semi-Private violin Class (2 Students, Different Levels)
POST http://localhost:5000/api/classes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTYzYmVkMjdlODljNjFkYmUzZTg1MSIsImlhdCI6MTc4NDM4NDk2OH0.eyUZ_naGULuPo1X3-a0CY5W_47LacjbSvuNvRKSp3Gw

{
  "teacherId": "6a563fae27e89c61dbe3e861",
  "zoneId": "6a5b8cd89aaa9d653d43920e",
  "startTime": "2026-07-20T14:00:00.000Z",
  "endTime": "2026-07-20T15:00:00.000Z",
  "note": "Semi-Private class session testing independent tracking tiers.",
  "enrolledStudents": [
    {
      "studentId": "6a563c9c27e89c61dbe3e858",
      "courseId": "6a5b89b29aaa9d653d439204",
      "level": 2
    },
    {
      "studentId": "6a563d2827e89c61dbe3e85a",
      "courseId": "6a5b89b29aaa9d653d439204",
      "level": 1
    }
  ]
}

### Schedule an Advanced group class
POST http://localhost:5000/api/classes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTYzYmVkMjdlODljNjFkYmUzZTg1MSIsImlhdCI6MTc4NDM4NDk2OH0.eyUZ_naGULuPo1X3-a0CY5W_47LacjbSvuNvRKSp3Gw

{
  "teacherId": "6a563f9327e89c61dbe3e85f",
  "zoneId": "6a5b50ba9c979cce44b25692",
  "startTime": "2026-07-20T14:00:00.000Z",
  "endTime": "2026-07-20T15:00:00.000Z",
  "note": "Semi-Private class session testing independent tracking tiers.",
  "enrolledStudents": [
    {
      "studentId": "6a563c7b27e89c61dbe3e855",
      "courseId": "6a5b8ad09aaa9d653d43920a",
      "level": 1
    },
    {
      "studentId": "6a563c8827e89c61dbe3e856",
      "courseId": "6a5b8ad09aaa9d653d43920a",
      "level": 1
    },
    {
      "studentId": "6a563c9427e89c61dbe3e857",
      "courseId": "6a5b8ad09aaa9d653d43920a",
      "level": 1
    },
    {
      "studentId": "6a563c9c27e89c61dbe3e858",
      "courseId": "6a5b8ad09aaa9d653d43920a",
      "level": 1
    }
  ]
}


### Add new student to group class
PATCH http://localhost:5000/api/classes/6a5b91cfb5f53f8e39316489/add-student
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTYzYmVkMjdlODljNjFkYmUzZTg1MSIsImlhdCI6MTc4NDM4NDk2OH0.eyUZ_naGULuPo1X3-a0CY5W_47LacjbSvuNvRKSp3Gw

{
  "studentId": "6a563cc727e89c61dbe3e859",
  "courseId": "6a5b8ad09aaa9d653d43920a",
  "level": 1
}

### Get teacher all classes
GET http://localhost:5000/api/classes/teacher/6a4908a2c0edb72d022e0419
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNGJhYzE1YzdlZDZkOTExN2M4NTc1MSIsImlhdCI6MTc4MzQxODY0N30.lnNuo6yYxNLOv0chUJtbiG7a6Pat7n3P4O5hM1STNh0