### User login to get token
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "somsri@school.com",
  "password": "password123"
}

### Create course category
POST http://localhost:5000/api/coursecategory
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDkwOGEyYzBlZGI3MmQwMjJlMDQxOSIsImlhdCI6MTc4MzI2MTMxOH0.3Uq8gOUmbqzl_JJi7WT_CaQ0Apj6gUC-520wxAts7pc

{
    "name":{
        "th": "กีตาร์",
        "en": "Guitar"
    },
    "description":{
        "th": "หลักสูตรวิชากีตาร์",
        "en": "Guitar course"
    }
}

### Register private piano course with levels
POST http://localhost:5000/api/courses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDkwOGEyYzBlZGI3MmQwMjJlMDQxOSIsImlhdCI6MTc4MzYwMzg1OX0.6fCwgF1AjgmwUCKUmZgOWViER7pzetePOpLqCB5b6R8

{
  "courseCategoryId": "6a4a6bf64b3ba514cc08c1ed",
  "title": {
    "th": "หลักสูตรเปียโนเด็กเล็ก",
    "en": "Junior Progressive Piano Track"
  },
  "description": {
    "th": "หลักสูตรฝึกทักษะนิ้วมือและสายตาแบ่งเป็นชุดตำราเรียนดนตรี",
    "en": " Progressive physical notation and rhythmic course syllabus."
  },
  "durationInMinutes": 60,
  "lessonType": "private",
  "levels": [
    { "level": 1, "levelName": "Book 1 - Green Primer", "price": 3200 },
    { "level": 2, "levelName": "Book 2 - Blue Beginner", "price": 3200 },
    { "level": 3, "levelName": "Book 3 - Orange Intermediate", "price": 3500 },
    { "level": 4, "levelName": "Grade 1 Masterpiece", "price": 4000 }
  ]
}

### Get all active courses
GET http://localhost:5000/api/courses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDkwOGEyYzBlZGI3MmQwMjJlMDQxOSIsImlhdCI6MTc4MzE4MDM3NX0.54CVeu4Tz8ESJVqCm4g-L0jvqysD5VxbOdknZw58Av8

### Get all active course categories
GET http://localhost:5000/api/coursecategory
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDkwOGEyYzBlZGI3MmQwMjJlMDQxOSIsImlhdCI6MTc4MzE4MDM3NX0.54CVeu4Tz8ESJVqCm4g-L0jvqysD5VxbOdknZw58Av8