### Register new school

POST http://localhost:5000/api/schools
Content-Type: application/json

{
  "schoolName": {
    "th": "โรงเรียนดนตรีสยามป๊อป สาขา 2",
    "en": "Siam Pop Music Academy - Second branch"
  },
  "schoolType": "music",
  "email": "contact@siampopmusic.com",
  "phoneNumber": "+6628889999",
  "address": {
    "th": "645 ถ.ลาดพร้าว เขตบางกะปิ กรุงเทพฯ 10500",
    "en": "645 Ladprao Rd, Bangkapi, Bangkok 10500"
  },
  "settings": {
    "currency": "THB",
    "timeZone": "Asia/Bangkok",
    "isVatEnabled": true,
    "vatRate": 7
  }
}

### Get school by ID
GET http://localhost:5000/api/schools/6a4684d8bbe327f841fbdcd3
